CREATE DATABASE TESTING;

USE TESTING;

CREATE TABLE USERS(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user VARCHAR(250) NOT NULL,
    pass VARCHAR(250) NOT NULL
);


INSERT INTO USERS ( user , pass ) VALUES ('admin','admin'), ('admin','0000');


SELECT * FROM USERS;